// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    id,
    created_at,
    updated_at,
    title,
    url,
    user_id
) VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3,
    $4
)
RETURNING id, created_at, updated_at, title, content, url, user_id
`

type CreateDocumentParams struct {
	ID     uuid.UUID
	Title  string
	Url    string
	UserID uuid.UUID
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.ID,
		arg.Title,
		arg.Url,
		arg.UserID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Content,
		&i.Url,
		&i.UserID,
	)
	return i, err
}
