// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    id,
    created_at,
    updated_at,
    title,
    user_id
) VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, title, content, user_id
`

type CreateDocumentParams struct {
	Title  string
	UserID uuid.UUID
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument, arg.Title, arg.UserID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Content,
		&i.UserID,
	)
	return i, err
}

const deleteDocumentByID = `-- name: DeleteDocumentByID :exec
DELETE FROM documents
    WHERE id = $1
`

func (q *Queries) DeleteDocumentByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentByID, id)
	return err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT 
    documents.id,
    documents.created_at,
    documents.updated_at,
    documents.title,
    documents.user_id as user_id,
    documents.content,
    users.display_name as owner,
    users.email as owner_email
FROM documents
JOIN users ON user_id = users.id
WHERE documents.id = $1
`

type GetDocumentByIDRow struct {
	ID         uuid.UUID
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	Title      string
	UserID     uuid.UUID
	Content    sql.NullString
	Owner      sql.NullString
	OwnerEmail string
}

func (q *Queries) GetDocumentByID(ctx context.Context, id uuid.UUID) (GetDocumentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByID, id)
	var i GetDocumentByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.UserID,
		&i.Content,
		&i.Owner,
		&i.OwnerEmail,
	)
	return i, err
}

const getDocumentsByOwner = `-- name: GetDocumentsByOwner :many
SELECT 
    documents.id,
    documents.created_at,
    documents.updated_at,
    documents.title,
    documents.user_id as user_id,
    users.display_name as owner,
    users.email as owner_email
FROM documents
JOIN users ON user_id = users.id
WHERE user_id = $1
ORDER BY documents.updated_at DESC
`

type GetDocumentsByOwnerRow struct {
	ID         uuid.UUID
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	Title      string
	UserID     uuid.UUID
	Owner      sql.NullString
	OwnerEmail string
}

func (q *Queries) GetDocumentsByOwner(ctx context.Context, userID uuid.UUID) ([]GetDocumentsByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentsByOwner, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentsByOwnerRow
	for rows.Next() {
		var i GetDocumentsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.UserID,
			&i.Owner,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentContentByID = `-- name: UpdateDocumentContentByID :one
UPDATE documents
SET content = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, title, content, user_id
`

type UpdateDocumentContentByIDParams struct {
	ID      uuid.UUID
	Content sql.NullString
}

func (q *Queries) UpdateDocumentContentByID(ctx context.Context, arg UpdateDocumentContentByIDParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocumentContentByID, arg.ID, arg.Content)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Content,
		&i.UserID,
	)
	return i, err
}

const updateDocumentTitleByID = `-- name: UpdateDocumentTitleByID :one
UPDATE documents
SET title = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, title, content, user_id
`

type UpdateDocumentTitleByIDParams struct {
	ID    uuid.UUID
	Title string
}

func (q *Queries) UpdateDocumentTitleByID(ctx context.Context, arg UpdateDocumentTitleByIDParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocumentTitleByID, arg.ID, arg.Title)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Content,
		&i.UserID,
	)
	return i, err
}
